---
- name: Harden IOS XE Devices
  hosts: iosxe
  connection: netconf
  gather_facts: false

  tasks:
    - name: 01 - Force SSH Version 2
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <ip>
                  <ssh>
                    <ssh-version>2</ssh-version>
                  </ssh>
                </ip>
              </native>
            </config>

    - name: 02 - Task to Enable Secure HTTPS CipherSuites
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <ip>
                  <http xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-http">
                    <secure-ciphersuite>
                      <dhe-aes-gcm-sha2/>
                      <ecdhe-ecdsa-aes-gcm-sha2/>
                      <ecdhe-rsa-aes-gcm-sha2/>
                      <tls13-aes128-gcm-sha256/>
                      <tls13-aes256-gcm-sha384/>
                      <tls13-chacha20-poly1305-sha256/>
                    </secure-ciphersuite>
                  </http>
                </ip>
              </native>
            </config>

    - name: 03 - Task to Add Common Criteria Policy
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <aaa>
                  <common-criteria xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-aaa">
                    <policy>COMMON-POLICY</policy>
                    <upper-case>1</upper-case>
                    <lower-case>1</lower-case>
                    <numeric-count>1</numeric-count>
                    <special-case>1</special-case>
                    <min-length>12</min-length>
                    <max-length>127</max-length>
                    <character-repetition>2</character-repetition>
                    <char-changes>3</char-changes>
                    <restrict-consecutive-letters/>
                  </common-criteria>
                </aaa>
              </native>
            </config>
            